In [1]:
#NumPy
#-> Memory consumption is really less
import numpy as np

In [2]:
l1= [1,2,3]
arr1= np.array([1,2,3])
print(l1)
print(arr1)

[1, 2, 3]
[1 2 3]


In [3]:
type(arr1)

numpy.ndarray

In [4]:
#Finding Dimension
arr1.ndim

1

In [5]:
#ARange
#-> printing a range of values
#-> Direct
np.arange(13,19)

array([13, 14, 15, 16, 17, 18])

In [6]:
#Indirect
range(13,19)

range(13, 19)

In [7]:
for i in range(13,19):
    print(i)

13
14
15
16
17
18


In [8]:
np.arange(13,40,3) #here 3 is the skip value

array([13, 16, 19, 22, 25, 28, 31, 34, 37])

In [9]:
np.arange(12,40,3,dtype= float)

array([12., 15., 18., 21., 24., 27., 30., 33., 36., 39.])

In [10]:
np.arange(13,40,3.5)

array([13. , 16.5, 20. , 23.5, 27. , 30.5, 34. , 37.5])

In [11]:
#Zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
#Ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.zeros(15), np.ones(13,dtype= int)

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

In [18]:
#LinSpace
np.linspace(0,10,5) #here 5 is the number of divisions to be made

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [20]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [22]:
#ArgMax -> Position of the maximum value
#ArgMin ->Position of the minimum value
arr= np.array([1,2,3,4,5,6,7,8,9])

In [23]:
arr.argmax()

8

In [24]:
arr.argmin()

0

In [31]:
a= np.array([5,2,1,3,5,4,1,5])

In [32]:
a.argmax() #->gives the 1st occuring index of the maximum element

0

In [33]:
a.argmin() #->gives the 1st occuring index of the minimum element

2

In [36]:
#Slicing and Indexing in the NumPy Array
a[1:4], a[3:7]

(array([2, 1, 3]), array([3, 5, 4, 1]))

In [37]:
a[-4:]

array([5, 4, 1, 5])

In [44]:
a[-8:8], a[-8:-1]

(array([5, 2, 1, 3, 5, 4, 1, 5]), array([5, 2, 1, 3, 5, 4, 1]))

In [45]:
a[-1:-4] #reverse doesnt work here

array([], dtype=int32)

In [63]:
b= np.array([[1,3,2,4], [9,8,6,7]])
b

array([[1, 3, 2, 4],
       [9, 8, 6, 7]])

In [64]:
b.ndim

2

In [66]:
b[0]

array([1, 3, 2, 4])

In [67]:
b[1][1] #since 2 dim

8

In [52]:
b= np.array([[[[[[1,2,3],[2,3,4],[55,44,33]]]]]])
b

array([[[[[[ 1,  2,  3],
           [ 2,  3,  4],
           [55, 44, 33]]]]]])

In [60]:
b[0][0][0][0]

array([[ 1,  2,  3],
       [ 2,  3,  4],
       [55, 44, 33]])

In [61]:
b[0][0][0][0][0]

array([1, 2, 3])

In [62]:
b[0][0][0][0][2][2] #since 6 dim

33

In [53]:
b.ndim #since-> 6 brackets

6

In [69]:
#Reshape-> reshaping the array dimension

a= np.arange(12) #Possible-> 6*2 or 2*6 and 4*3 or 3*4
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [71]:
a.reshape(6,2), a.reshape(2,6)

(array([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]]),
 array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]))

In [73]:
a.reshape(4,3),a.reshape(3,4)

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]))

In [74]:
a.reshape(10,4) #error, since 10*4 = 40, so we need 40 values, 12 wont work

ValueError: cannot reshape array of size 12 into shape (10,4)

In [75]:
#Generation of random values
np.random.rand()

0.4158945768199208

In [76]:
np.random.rand(5) #5 random values

array([0.41119682, 0.15328441, 0.76331811, 0.03154145, 0.50851866])

In [80]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [81]:
a.sum() #Gives sum of all the values in array a

66

In [82]:
 #Log values
np.log(a)

C:\Users\balod\AppData\Local\Temp\ipykernel_25900\974705729.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527])

In [83]:
np.log10(a)

C:\Users\balod\AppData\Local\Temp\ipykernel_25900\547625357.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(a)


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251,
       1.        , 1.04139269])

In [84]:
#Absolute values
np.abs(-33)

33

In [85]:
a= np.array([-2,-5,-55,-44])

In [86]:
np.abs(a)

array([ 2,  5, 55, 44])

In [87]:
#Pandas-> Data Manipulation
#-> Series -> single column (ex- vector)
#-> Data Frame -> multiple columns (ex- tablular form)
import pandas as pd

In [92]:
#Series
#-> Indexing and slicing are possible
#-> Mutable (values can be modified)
#-> Index values can be changed

s= pd.Series(np.random.rand(5))
s

0    0.598234
1    0.574244
2    0.111897
3    0.575362
4    0.345743
dtype: float64

In [93]:
s[0]

0.5982341310415563

In [94]:
s[1:4]

1    0.574244
2    0.111897
3    0.575362
dtype: float64

In [97]:
s[-4:4] #same as arrays in np

1    0.574244
2    0.111897
3    0.575362
dtype: float64

In [98]:
s[-5:-1]

0    0.598234
1    0.574244
2    0.111897
3    0.575362
dtype: float64

In [99]:
s[0]= 222
s

0    222.000000
1      0.574244
2      0.111897
3      0.575362
4      0.345743
dtype: float64

In [100]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [103]:
s.index= ['a', 'b','c',4,'e'] #mixed index

In [104]:
s.index

Index(['a', 'b', 'c', 4, 'e'], dtype='object')

In [105]:
s['b']

0.5742438506403734

In [107]:
s['a'], s['b':'e'] #in string indexing, all the values including last is printed
#unlike integer indexing where last value is always skipped

(222.0,
 b    0.574244
 c    0.111897
 4    0.575362
 e    0.345743
 dtype: float64)

In [108]:
s[1:5] #slicing works in numbers as well

b    0.574244
c    0.111897
4    0.575362
e    0.345743
dtype: float64

In [110]:
s2= pd.Series(np.random.rand(12))
s2

0     0.392711
1     0.218800
2     0.189111
3     0.493162
4     0.069338
5     0.329444
6     0.333542
7     0.842533
8     0.703948
9     0.141206
10    0.238858
11    0.360285
dtype: float64

In [111]:
s2[1:10:2] #step value=2

1    0.218800
3    0.493162
5    0.329444
7    0.842533
9    0.141206
dtype: float64

In [112]:
s['a':'e':2]

a    222.000000
c      0.111897
e      0.345743
dtype: float64